version: "3"
services:
  app:
    container_name: qc_search_app
    build: .
    volumes:
      - .:/qc_search:delegated
    depends_on:
      - db
      - elasticsearch
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    env_file:
      - ".env"
    command: foreman start

  db:
    container_name: qc_search_db
    restart: always
    image: postgres:11
    volumes:
      - ./data/postgres/db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    env_file:
      - ".env"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: qc_search_elastic
    environment:
      - discovery.type=single-node
      - cluster.name=qsearch_elastic-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data:delegated
    ports:
      - 9200:9200
    env_file:
      - ".env"
