version: "3"
services:
  app:
    container_name: qc_search_app
    build: .
    volumes:
      - .:/qc_search:delegated
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    env_file:
      - ".env"
    command: foreman start
